# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unit Test and E2E Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build --if-present

    - name: Run Unit Tests with coverage
      run: npm run test:cov
      env:
        CI: true

    - name: Upload Unit Test Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-coverage
        path: coverage/clover.xml

    - name: Run E2E Tests
      run: npm run test:e2e
      env:
        CI: true

    - name: Upload E2E Test Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-coverage
        path: test/reports/junit/junit.xml
