# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unit Test and E2E Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      DEV_REFRESH_TOKEN: ${{ secrets.DEV_REFRESH_TOKEN }}
      PROD_REFRESH_TOKEN: ${{ secrets.PROD_REFRESH_TOKEN }}
      DEV_ACCESS_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN }}
      PROD_ACCESS_TOKEN: ${{ secrets.PROD_ACCESS_TOKEN }}
      DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
      PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
      SWAGGER_USER: ${{ secrets.SWAGGER_USER }}
      SWAGGER_PASSWORD: ${{ secrets.SWAGGER_PASSWORD }}

    strategy:
      matrix:
        node-version: [22.5.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Truncate All Tabels
      run: npx prisma db execute --file=prisma/truncate-data.sql

    - name: Seed Database
      run: npx prisma db seed

    - name: Build project
      run: npm run build --if-present

    - name: Run Unit Tests with coverage
      run: npm run test:cov
      env:
        CI: true

    - name: Upload Unit Test Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-coverage
        path: coverage/clover.xml

    - name: Run E2E Tests
      run: |
        npx jest --config ./test/jest-e2e.json --testPathPattern=01-auth-controller.e2e-spec.ts
        npx jest --config ./test/jest-e2e.json --testPathPattern=02-user-controller-admin.e2e-spec.ts
        npx jest --config ./test/jest-e2e.json --testPathPattern=03-auth-new-user.e2e-spec.ts
      env:
        CI: true

    - name: Upload E2E Test Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-coverage
        path: test/reports/junit/junit.xml
